#!/bin/bash

echo "SNOPS_REVEALJS_DEV=$SNOPS_REVEALJS_DEV"

for i in css js lib plugin
do
	echo "Linking /home/snops/$i to /home/snops/reveal-js/$i"
	ln -s /home/snops/reveal-js/$i /home/snops
done

if [ $SNOPS_REVEALJS_DEV == 1 ]; then
	echo "Installing Reveal.js Dev Tools..."
	apk add g++
	npm install
	npm start &
fi
