#!/bin/bash
set -e

cd /etc/vim/vim_runtime

echo 'set runtimepath+=/etc/vim/vim_runtime

source /etc/vim/vim_runtime/vimrcs/basic.vim
source /etc/vim/vim_runtime/vimrcs/filetypes.vim
source /etc/vim/vim_runtime/vimrcs/plugins_config.vim
source /etc/vim/vim_runtime/vimrcs/extended.vim

try
source /etc/vim/vim_runtime/my_configs.vim
catch
endtry' > /etc/vim/vimrc.ultimate

echo 'set background=light
set number
set background=dark' > /etc/vim/vim_runtime/my_configs.vim

ln -s /etc/vim/vimrc.ultimate /root/.vimrc
ln -s /etc/vim/vimrc.ultimate /home/snops/.vimrc


echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"