#!/bin/bash

echo "Reticulating splines..."
ln -s /usr/bin/sphinx-build-2 /usr/bin/sphinx-build

echo "Becoming self-aware..."
/snopsboot/cloneGitRepos.sh

chown -Rf snops:snops /home

export SNOPS_HOST_IP=`/sbin/ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`
echo "SNOPS_HOST_IP=$SNOPS_HOST_IP" >> /snopsboot/SNOPS_ENV
echo "SNOPS_HOST_HTTP=$SNOPS_HOST_HTTP" >> /snopsboot/SNOPS_ENV
echo "SNOPS_HOST_SSH=$SNOPS_HOST_SSH" >> /snopsboot/SNOPS_ENV

cat /etc/motd

/bin/bash --login
