#!/bin/bash

cd framework
npm install
npm run build
cd f5-newman-wrapper
npm install
ln -s /home/f5-postman-workflows/framework/f5-newman-wrapper/f5-newman-wrapper /usr/bin/f5-newman-wrapper

if [ -d /host_share ]; then
	ln -s /host_share /home/f5-postman-workflows/host_share
fi
