#!/bin/sh

s6-setuidgid 1001:1001 sh -c 'JENKINS_SLAVE_AGENT_PORT=50000 \
JENKINS_HOME=/var/jenkins_home \
COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log \
JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Djenkins.CLI.disabled=true" \
/usr/local/bin/jenkins.sh >> /var/jenkins_home/jenkins.log 2>&1'